### ISSUE TITLE
DecryptESD will look for the key xml file inside the current directory instead of the executable location.

### ISSUE THREAD

**Issue by gus33000** [hounsell/DecryptESD#3]
It should look for that file inside the executable directory instead of the current directory or add an option to specify the location of that file. The current implementation makes it annoying since if the current directory isn't DecryptESD location, the program will fail to find the file.

Here's the stack trace:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\gus33000\Documents\GitHub\ESD-Decrypter\CryptoKeys.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at DecryptESD.CryptoKey.LoadKeysFromXml()
   at DecryptESD.Program.Main(String[] args)
```

DecryptESD is in the C:\Users\gus33000\Documents\GitHub\ESD-Decrypter\bin directory in this case

**Comment by hounsell** [comment]
I've DM'd you a link to a new binary of the latest v0.4 code. Could you confirm this bug is fixed?
